# Generated by Django 4.2.3 on 2023-07-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('matricula', models.CharField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoP', models.CharField(max_length=50)),
                ('apellidoM', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('correo', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id_conv', models.IntegerField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=30)),
                ('proceso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.CharField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('nomb_enlace', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=80)),
                ('cargo_titular', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=10)),
                ('usuarioE', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_proy', models.CharField(max_length=80)),
                ('modalidad', models.CharField(max_length=50)),
                ('asesor', models.CharField(max_length=80)),
                ('carrera', models.CharField(max_length=100)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BEV2.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno_Cov_Proy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=100)),
                ('id_alum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BEV2.alumnos')),
                ('id_cov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BEV2.convocatoria')),
                ('id_proy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BEV2.proyecto')),
            ],
        ),
    ]
