# Generated by Django 4.2.3 on 2023-07-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEV2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='password',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='passwordE',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
